baseURL = "https://do1ph.in"
title = "junghyun397 Blog"
theme = "hugo-notepadium"
copyright = "©2020 junghyun397."

languageCode = "ko-kr"
hasCJKLanguage = true

enableRobotsTXT = true

pygmentsCodefences = true
pygmentsStyle = "pygments"

# Enable Disqus
disqusShortname = "do1phin"

# Google Analytics
googleAnalytics = "UA-158778546-1"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[params]
style = "auto"
logo = ""
slogan = "Maybe JeongHyeon Choi's blog."

[params.assets]
css = ["css/custom-style.css"]

[params.comments]
enable = true

[params.math]
enable = true
use = "katex"

[params.syntax]
use = true
theme = "xcode"
darkTheme = "xcode-dark"

[params.nav]
showCategories = true
showTags = true

# custom navigation items

[[params.nav.custom]]
title = "Categories"
url = "/categories"

[[params.nav.custom]]
title = "Tgas"
url = "/tags"

[[params.nav.custom]]
title = "About"
url = "/about"

[[params.nav.custom]]
title = "Github"
url = "https://github.com/junghyun397"

