name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: peaceiris/actions-hugo@v2
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GH_ACTIONS_PRIVATE_KEY }}
          known_hosts: "no"
      - name: "HUGO build"
        run: hugo -D
      - name: "Git configuration"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: "Push to repository"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "rebuilding site `date`"
          git pull --rebase origin master
          git push origin master
        working-directory: "public"
