name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{secrets.ACTIONS_TOKEN}}
      - uses: peaceiris/actions-hugo@v2
      - name: HUGO build
        run: hugo -D
      - name: Push to repository
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "rebuilding site `date`"
          git pull --rebase origin master
          git push https://github-actions[bot]:$ACTIONS_TOKEN@github.com/$REPO_OWNER/$REPO_OWNER.github.io.git "HEAD:refs/heads/master"
        env:
          REPO_OWNER: ${{github.repository_owner}}
          ACTIONS_TOKEN: ${{secrets.ACTIONS_TOKEN}}
        working-directory: public
