name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: peaceiris/actions-hugo@v2
      - name: "HUGO build"
        run: hugo -D
      - name: "Push to repository"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "rebuilding site `date`"
          git pull --rebase origin master
          git push https://github-actions:$REPO_KEY@github.com/junghyun397/junghyun397.github.io.git
        working-directory: "public"
        env:
          REPO_KEY: ${{secrets.GH_ACTIONS_PRIVATE_KEY}}
        
